### ISSUE TITLE
imread() function in utils.py

### ISSUE THREAD

**Issue by 07Agarg** [kweisamx/SRCNN#1]
Hi @kweisamx ,

I am trying to replicate the same paper SRCNN. And just found your repo to be useful. You have used
img = cv2.imread(path) for reading the image file and in prepocess() function never converted it to YCbCr format as mentioned in the paper. 
I have gone through the references tegg89/SRCNN-Tensorflow you have mentioned in your Readme.md. In this repo also, they converted it to YCbCr format using scipy.misc.imread(path, mode='YCbCr').astype(np.float). 

Also, since you have converted image files to sub-images and stored in h5 format first, I didn't do the same. If this code did work for you, please check my repo https://github.com/07Agarg/Image-Resolution-Enhancement-SRCNN and suggest edits accordingly.

**Comment by kweisamx** [comment]
Hi @07Agarg Thanks for your suggestion.
The repo is created when I was a student, so I think it may have a lot of bug and mistake.
And now I have job and no much time to fix it, if I have free time i will fix.
Thanks for your suggestion again, and welcome to send issue and PR for my repo!
